CREATE DATABASE IF NOT EXISTS chess;
USE chess;

CREATE TABLE users (
 id INT AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(50) UNIQUE,
 password VARCHAR(255),
 rating INT DEFAULT 1200,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE games (
 id INT AUTO_INCREMENT PRIMARY KEY,
 white_player INT,
 black_player INT,
 fen TEXT,
 pgn TEXT,
 status VARCHAR(20),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE moves (
 id INT AUTO_INCREMENT PRIMARY KEY,
 game_id INT,
 move VARCHAR(20),
 fen TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);